package(default_visibility = ["//visibility:public"])

load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")

cc_grpc_library(
name = "hello_world",
srcs = [":hello_world.proto"],
#deps = ["@com_google_protobuf//:any_proto"],
deps = [],
)